### PR TITLE
Verify hashes during download.

### PR DESCRIPTION
**Pull request by GeorgiosSmyrnis**
This PR verifies the hash of an image provided by the input data in the parquet file. As a design decision, these hashes are not explicitly saved, rather overridden by the compute_hash argument (which defaults to sha256).

This PR builds upon #198 (credit to Nicholas Carlini), extending it with further hashes.

### CODE REVIEW

**Comment by rom1504** [comment]
Could you run it and check it works ? (Once to get a collection with hashes , second time to use it)
Maybe on sbucaption for example

**Comment by rom1504** [comment]
So I tried this and getting 15% error rate

not sure what to do next

**Comment by rom1504** [comment]
ok to do here:
* document laion5B with hash collection in examples
* explain it doesn't fully solve the problem as many images have different md5 hash but almost same content ; so probably don't advise it

**Comment by rom1504** [comment]
I think adding an option to compute phash (https://gist.github.com/rom1504/68e62921b1728f9e0539df7345eed8a8) could be nice

**Comment by rom1504** [comment]
thanks @GeorgiosSmyrnis and @carlini for implementing this

I added a few notes and exposed a version of laion5B containing the hashes

as of today, this is dropping 15% of the dataset, so I'm leaving it off by default but pointing people to how they can enable this.

**Comment by carlini** [comment]
Sounds reasonable. Thanks!

**Pull request merged**
