### PR TITLE
feat: allow encoding in different formats

### PR DESCRIPTION
**Pull request by borisdayma**
Allows encoding in different formats:

* jpeg: default
* png
* webp

TODO:
* [ ] use it on some datasets: ongoing

### CODE REVIEW

**Comment by rom1504** [comment]
To do here:
* Adapt the tests
* Optionally : add some numbers of space taken by each format in readme

**Comment by rom1504** [comment]
In the resizer test, could you add a set of params there https://github.com/rom1504/img2dataset/blob/main/tests/test_resizer.py#L23 to test all the output formats ?
To make sure encoding them works and keep working

**Comment by rom1504** [comment]
Other than that, this looks pretty much ready.
Anything you'd like to test /add before merging?

**Comment by rom1504** [comment]
Ah i guess one thing I'm wondering is whether there are significant difference of performance while using the different formats.
If you happen to run that benchmark, that would definitely be useful information to share.
But otherwise we can figure this out later on, after this PR

**Comment by borisdayma** [comment]
I think it should be good to merge. I played with it and it seems to work well.
As for knowing if there's any issue with webp I plan to make a report today or tomorrow and share it so we'll see what people comment on.

**Pull request merged**
