### PR TITLE
[distribution with pyspark]: changed the way we detect active session to support all version of pyspark

### PR DESCRIPTION
**Pull request by nateagr**

### CODE REVIEW

**Comment by rom1504** [comment]
could you fix the lint ?

see https://github.com/rom1504/img2dataset#for-development as to how

**Comment by nateagr** [comment]
> could you fix the lint ?
> 
> see https://github.com/rom1504/img2dataset#for-development as to how

Done !

**Comment by nateagr** [comment]
Hello @rom1504 ! What do you thing of the PR ?

**Comment by rom1504** [comment]
lgtm thanks

**Comment by rom1504** [comment]
out of curiosity did you manage to run it on the cluster ?

**Comment by nateagr** [comment]
> out of curiosity did you manage to run it on the cluster ?

Yes :) Much faster as I distribute the job on multi-machines vs multi-processes but mono-machine

**Pull request merged**
