### PR TITLE
feat: support min image size + max aspect ratio

### LINKED ISSUE #41: min/max file size + width/height ratio requirements
Would you handle things such as:
* min file size: so that we don't download images of low quality
* max file size: I sometimes see people checking Content-Length to prevent from DDOS attacks
* min/max image dimensions ratio such as 2:1 between width & height

Or do you consider this kind of filtering as a subsequent step?

### PR DESCRIPTION
**Pull request by borisdayma**
This allows keeping only images above certain dimensions and with a max aspect ratio.
fixes #41

The limit on file sizes were not implemented as it may be less straightforward to justify.

TODO:
* [x] perform some manual tests

### CODE REVIEW

**Comment by borisdayma** [comment]
The main use is for downloading large datasets, we can directly discard images we don't plan to use later (potentially a high percentage if we require only high resolution images for example)

**Comment by rom1504** [comment]
Could you 
* Add a test there https://github.com/rom1504/img2dataset/blob/main/tests/test_resizer.py (probably a new test function)
* update the readme with that new option
* Put a warning in the readme saying that using that option will likely result in non uniform shards 

Other than that, sounds good

**Comment by rom1504** [comment]
Also this shouldn't be used for laion as the height and width are known there so it's possible and better to pre filter the metadata

**Comment by borisdayma** [comment]
Yeah the use case I'm thinking with LAION is if the image was on a e-commerce site for example and then was replaced with a small placeholder (because the product disappeared)

**Comment by rom1504** [comment]
Sounds good but it should be done only after initial pre filtering of the metadata. That way you would only discard a small amount of images at download time and it wouldn't affect the shard distribution too much (and you would download a lot less which is faster)

Let's add this to do the doc of this feature imo

**Comment by rom1504** [comment]
Perfect, thanks!

**Pull request merged**
