### PR TITLE
feat: use albumentations for resizing

### PR DESCRIPTION
**Pull request by borisdayma**
Use albumentations for resizing functions

### CODE REVIEW

**Comment by borisdayma** [comment]
I noticed my formatter (black) changed a bit the layout.
Let me know what you use and I can change it back.

**Comment by borisdayma** [comment]
Fixed a test. When we keep the ratio and resize only if bigger, we need to have only one side smaller than the desired size.

Otherwise an image 100 x 200 would be resized to 150 x 250 (with a desired size of 150).

This is the same logic for center crop.

**Comment by borisdayma** [comment]
@rom1504 I can do #27 after you merge this one if you want

**Review by rom1504 — APPROVED** [review]
I tested it on 300k sample, memory is still behaving as before and speed is also same as before
the output looks good

thanks!

**Pull request merged**
