### PR TITLE
Enhance image resize processing (esp re downscale)

### PR DESCRIPTION
**Pull request by rwightman**
* add support for different downsample and upsample interpolation (area only interpolation for dowsample that is reasonable without extra filtering as Pillow does)
* add ability to skip re-encode for jpg data with size that fits target already (reduce CPU and avoid quality loss for an unecessary encode)
* pass jpeg encode quality through as arg, cv2 default is 95, lower is likely good enough for many uses (and far less impact than bad downsample choice)
* ResizeMode enum instead of strings
* use functional Albumentations for resize ops

### CODE REVIEW

**Comment by rwightman** [comment]
hmm, I think that fail is a false positive for the linter, https://docs.python.org/3/library/enum.html#iteration checking Enum.__members__ should be fine...

**Comment by rom1504** [comment]
thanks!

**Comment by borisdayma** [comment]
Why isn't skip_reencode always True?

**Comment by rom1504** [comment]
I assume that was to keep the previous behavior but indeed I see no drawback to make it true by default.
what do you think @rwightman ?

**Comment by borisdayma** [comment]
I'm wondering if there's even a reason for letting users make it false

**Comment by rom1504** [comment]
reencoding allows controlling the encoding quality even if no resizing is needed

**Pull request merged**
