### PR TITLE
Add support for cropping MidJourney style 4x4 grids

### PR DESCRIPTION
**Pull request by ehsan**
In order to use this, make sure to

1. Have a `crop` field in the source dataset (e.g. the source parquet file).  Current supported values are `top-left`, `top-right`, `bottom-left` and `bottom-right`).
2. Pass `--crop_mode field` to `img2dataset` and make sure you are NOT passing `--disable_all_reencoding true`.

### CODE REVIEW

**Comment by ehsan** [comment]
Oops sorry I opened this accidentally :(

**Comment by rom1504** [comment]
seems interesting, why not pr it ?

**Comment by ehsan** [comment]
this is something I put together for a specific dataset, I didn't mean to make it public in the first place, sorry :(

**Comment by ehsan** [comment]
Github UI was confusing and I didn't realize that our repo is a fork from yours.

**Comment by ehsan** [comment]
my apologies

**Pull request closed without merging**
