### PR TITLE
add list of int, float feature in TFRecordSampleWriter

### PR DESCRIPTION
**Pull request by justHungryMan**
We use list of int, list of float attribute in [coyo-labeled-300m](https://github.com/kakaobrain/coyo-dataset) dataset. (It will be released soon)
To create a dataset using img2dataset in tfrecord, we need to add above features.

### CODE REVIEW

**Comment by rom1504** [comment]
Can you please run make lint to fix the lint ?

**Comment by rom1504** [comment]
Thanks,
Could we also support list of bytes ?
I need that feature for laion translated

Also it would be great to add a few test samples with additional columns being list of x in the test folder and use them there https://github.com/rom1504/img2dataset/blob/main/tests/test_writer.py to make sure it works and keeps working

**Comment by justHungryMan** [comment]
@rom1504 Ok, it's good idea.
And I tried linting with black, but other parts that I didn't change were linted also. Maybe I'm using it wrong?

**Comment by rom1504** [comment]
Yeah create a venv and do make install-dev

You probably have the wrong version of black

**Comment by justHungryMan** [comment]
I just added dummy sample in test_writer.py.

**Comment by rom1504** [comment]
thank you, looking good!

**Pull request merged**
