### PR TITLE
fix(example): move python code into __main__

### PR DESCRIPTION
**Pull request by Adenialzz**
python multiprocessing code need to run in \_\_main\_\_

### CODE REVIEW

**Comment by rom1504** [comment]
in what case does this change something?

**Comment by rom1504** [comment]
https://stackoverflow.com/questions/74530990/how-to-run-multiprocessing-pool-code-in-python-without-mentioning-main-envir apparently that's useful only in windows

I don't think img2dataset really works in windows anyway

do you have another use case?

**Comment by Adenialzz** [comment]
Have you tested that on Linux? I run this example script on Linux and got the error seems like https://github.com/rom1504/img2dataset/issues/176. After I put this code snippet into \_\_main\_\_, it works.

**Comment by rom1504** [comment]
Yes it works for me.

What distribution are you using?

**Comment by Adenialzz** [comment]
default multiprocessing

**Comment by rom1504** [comment]
ah I meant what linux distribution

**Comment by Adenialzz** [comment]
Ubuntu 18.04.3 LTS

**Pull request merged**
