### PR TITLE
Avoid downloading duplicate

### PR DESCRIPTION
**Pull request by JRBusiness**
A quick update to avoid downloading duplicate images

### CODE REVIEW

**Comment by rom1504** [comment]
That is not going to work at scale and will make the code slow
The best way to do this is to remove images from the input file

**Comment by JRBusiness** [comment]
Right, I removed dup check but added history base check.

**Comment by rom1504** [comment]
I want this package to scale. It currently works up to 400M samples, i intend for it to work for a few billions next.
Adding an "history check" in that way will not scale.

I don't think there is any way but to have a job before that script to do the filtering of the input

We could consider providing that script as another file / command in this repo.

**Comment by heurainbow** [comment]
I made a hot fix for the laion400m dataset [here](https://github.com/heurainbow/img2dataset) . Maybe you can consider this solution for other formats.
1 resume flag
2 it is a valid resume if both meta parquet and tar file exists in each downloader thread
3 for a valid resume downloading thread, filter out those not downloaded yet and only download this into a resume.tar
4 append resume.tar to original tar to get a new tar.

It now only works for fixed dataset resuming with the exact same command.

I use this feature to maintain image number as the original order.

**Comment by JRBusiness** [comment]
I did ran the script and the performance with or without history check isnt much different.

**Comment by rom1504** [comment]
the problem here was putting everything in memory. That doesn't work for 400M samples

I will implement a better solution for this

thanks for the PR anyway!

**Pull request closed without merging**
